version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.4
    commands:
      - echo "=== INSTALL PHASE ==="
      - echo "Installing PHP and Composer..."
      - php --version
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - composer --version
      
  pre_build:
    commands:
      - echo "=== PRE-BUILD PHASE ==="
      - echo "Build started on `date`"
      - echo "Installing PHPUnit and dependencies..."
      - composer install --no-interaction --prefer-dist --optimize-autoloader
      - ls -la
      
  build:
    commands:
      - echo "=== BUILD PHASE ==="
      - echo "🧪 Running PHPUnit tests..."
      
      - echo "1. File existence tests..."
      - test -f index.html || (echo "❌ index.html not found" && exit 1)
      - test -f style.css || (echo "❌ style.css not found" && exit 1)
      - test -f script.js || (echo "❌ script.js not found" && exit 1)
      - echo "✅ All required files exist"
      
      - echo "2. Content validation tests..."
      - grep -q "CodePipeline S3 Demo" index.html || (echo "❌ Title not found" && exit 1)
      - grep -q "body" style.css || (echo "❌ CSS body not found" && exit 1)
      - echo "✅ Content validation passed"
      
      - echo "3. Running PHPUnit tests..."
      - ./vendor/bin/phpunit --verbose --testdox
      - echo "✅ PHPUnit tests passed"
      
      - echo "4. PHP syntax validation..."
      - find . -name "*.php" -exec php -l {} \; || (echo "❌ PHP syntax error" && exit 1)
      - echo "✅ PHP syntax validation passed"
      
      - echo "🏗️ Building static website..."
      - echo "Processing files..."
      
  post_build:
    commands:
      - echo "=== POST-BUILD PHASE ==="
      - echo "🎉 All PHPUnit tests passed! Build completed on `date`"
      - echo "Files ready for deployment:"
      - ls -la

reports:
  phpunit_reports:
    files:
      - 'tests/results/junit.xml'
    file-format: 'JUNITXML'
    base-directory: '.'
      
artifacts:
  files:
    - '**/*'
  exclude-paths:
    - vendor/**/*
    - '*.log'
  name: static-website-phpunit-$(date +%Y-%m-%d-%H-%M-%S)
