version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "=== INSTALL PHASE ==="
      - echo "Installing dependencies..."
      - npm install
      
  pre_build:
    commands:
      - echo "=== PRE-BUILD PHASE ==="
      - echo "Build started on `date`"
      - echo "Running pre-build validations..."
      - ls -la
      
  build:
    commands:
      - echo "=== BUILD PHASE ==="
      - echo "🧪 Running automated tests..."
      
      - echo "1. File existence tests..."
      - test -f index.html || (echo "❌ index.html not found" && exit 1)
      - test -f style.css || (echo "❌ style.css not found" && exit 1)
      - test -f script.js || (echo "❌ script.js not found" && exit 1)
      - echo "✅ All required files exist"
      
      - echo "2. Content validation tests..."
      - grep -q "CodePipeline S3 Demo" index.html || (echo "❌ Title not found" && exit 1)
      - grep -q "body" style.css || (echo "❌ CSS body not found" && exit 1)
      - echo "✅ Content validation passed"
      
      - echo "3. Running Jest unit tests..."
      - npm test
      - echo "✅ Unit tests passed"
      
      - echo "🏗️ Building static website..."
      - echo "Processing files..."
      
  post_build:
    commands:
      - echo "=== POST-BUILD PHASE ==="
      - echo "🎉 All tests passed! Build completed on `date`"
      - echo "Files ready for deployment:"
      - ls -la
      
artifacts:
  files:
    - '**/*'
  exclude-paths:
    - node_modules/**/*
    - '*.log'
  name: static-website-tested-$(date +%Y-%m-%d-%H-%M-%S)
