version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      php: 7.4
    commands:
      - echo "Installing dependencies"
      - npm install
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - composer install --no-interaction --prefer-dist --optimize-autoloader
      
  pre_build:
    commands:
      - echo "Pre-build phase"
      - ls -la
      
  build:
    commands:
      - echo "Build phase"
      - echo "File existence tests"
      - test -f index.html || exit 1
      - test -f style.css || exit 1
      - test -f script.js || exit 1
      - echo "Content validation"
      - grep -q "CodePipeline S3 Demo" index.html || exit 1
      - grep -q "body" style.css || exit 1
      - echo "Running Jest tests"
      - npm test
      - echo "Running PHPUnit tests"
      - mkdir -p tests/results
      - ./vendor/bin/phpunit --verbose
      - echo "PHP syntax check"
      - find tests -name "*.php" -exec php -l {} \;
      
  post_build:
    commands:
      - echo "Post-build phase"
      - echo "All tests completed"
      - ls -la

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - node_modules/**/*
    - vendor/**/*
